<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ParkingSubscription.Application\ParkingSubscription.Application.csproj" />
    <ProjectReference Include="..\ParkingSubscription.Infrastructure\ParkingSubscription.Infrastructure.csproj" />
    <ProjectReference Include="..\ParkingSubscription.Domain\ParkingSubscription.Domain.csproj" />
  </ItemGroup>

</Project>
