// <auto-generated> — SKIDATA sweb Subscribe API model (do not edit by hand).
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace ParkingSubscription.Api.Subscribe;

[GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
public partial class Address
{
    /// <summary>
    /// the first line of the address.
    /// </summary>
    [JsonProperty("lineOne", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
    [StringLength(64)]
    public string LineOne { get; set; }

    /// <summary>
    /// the second line of the address
    /// </summary>
    [JsonProperty("lineTwo", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
    [StringLength(64)]
    public string LineTwo { get; set; }

    /// <summary>
    /// the third line of the address
    /// </summary>
    [JsonProperty("lineThree", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
    [StringLength(64)]
    public string LineThree { get; set; }

    /// <summary>
    /// the fourth line of the address
    /// </summary>
    [JsonProperty("lineFour", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
    [StringLength(64)]
    public string LineFour { get; set; }

    /// <summary>
    /// the ZIP code of the city. If not set will default to the same as the facility when in Parking
    /// </summary>
    [JsonProperty("zipcode", Required = Required.Always)]
    [Required(AllowEmptyStrings = true)]
    [StringLength(16)]
    public string Zipcode { get; set; }

    /// <summary>
    /// the city name. If not set will default to the same as the facility when in Parking
    /// </summary>
    [JsonProperty("city", Required = Required.Always)]
    [Required(AllowEmptyStrings = true)]
    [StringLength(64)]
    public string City { get; set; }

    /// <summary>
    /// the region name
    /// </summary>
    [JsonProperty("region", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
    [StringLength(25)]
    public string Region { get; set; }

    /// <summary>
    /// the country code as ISO code
    /// </summary>
    [JsonProperty("country", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
    [StringLength(2)]
    public string Country { get; set; }

    private IDictionary<string, object> _additionalProperties;

    [JsonExtensionData]
    public IDictionary<string, object> AdditionalProperties
    {
        get { return _additionalProperties ?? (_additionalProperties = new Dictionary<string, object>()); }
        set { _additionalProperties = value; }
    }

}
