// <auto-generated> — SKIDATA sweb Subscribe API model (do not edit by hand).
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace ParkingSubscription.Api.Subscribe;

[GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
public partial class Communication
{
    /// <summary>
    /// flag indicating if the contact accepts the usage of their personal data. Mapped to AcceptUsageOfPersonalData
    /// </summary>
    [JsonProperty("marketing", Required = Required.Always)]
    public bool Marketing { get; set; }

    /// <summary>
    /// flag indicating if the contact accepts the submission of their personal data to 3rd parties
    /// </summary>
    [JsonProperty("thirdParties", Required = Required.Always)]
    public bool ThirdParties { get; set; }

    /// <summary>
    /// the flag indicating if mailing contact is accepted
    /// </summary>
    [JsonProperty("mailing", Required = Required.Always)]
    public bool Mailing { get; set; }

    private IDictionary<string, object> _additionalProperties;

    [JsonExtensionData]
    public IDictionary<string, object> AdditionalProperties
    {
        get { return _additionalProperties ?? (_additionalProperties = new Dictionary<string, object>()); }
        set { _additionalProperties = value; }
    }

}
