// <auto-generated> — SKIDATA sweb Subscribe API model (do not edit by hand).
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace ParkingSubscription.Api.Subscribe;

[GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
public partial class Contact : Details
{
    /// <summary>
    /// an external ID of the contact
    /// </summary>
    [JsonProperty("externalContactId", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
    [StringLength(32)]
    public string ExternalContactId { get; set; }

    /// <summary>
    /// what is the users website
    /// </summary>
    [JsonProperty("website", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
    [StringLength(64)]
    public string Website { get; set; }

    [JsonProperty("address", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
    public Address Address { get; set; }

    [JsonProperty("communication", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
    public Communication Communication { get; set; }

    [JsonProperty("photo", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
    public Photo Photo { get; set; }

    [JsonProperty("department", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
    public Department Department { get; set; }

    /// <summary>
    /// Lets you enter the tax reference number.
    /// </summary>
    [JsonProperty("taxNumber", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
    [StringLength(16)]
    public string TaxNumber { get; set; }

}
