// <auto-generated> — SKIDATA sweb Subscribe API model (do not edit by hand).
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace ParkingSubscription.Api.Subscribe;

[GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
public partial class CreateUser : Contact
{
    [JsonProperty("groupCustomerId", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
    public Guid? GroupCustomerId { get; set; }

    [JsonProperty("b2bCustomerId", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
    public Guid? B2bCustomerId { get; set; }

    [JsonProperty("licensePlates", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
    public ICollection<LicensePlate> LicensePlates { get; set; }

    [JsonProperty("identifications", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
    public ICollection<Identification> Identifications { get; set; }

    [JsonProperty("parkingContract", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
    public UserParkingContract ParkingContract { get; set; }

}
