// <auto-generated> — SKIDATA sweb Subscribe API model (do not edit by hand).
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace ParkingSubscription.Api.Subscribe;

[GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
public partial class CustomerParkingContract : UserParkingContract
{
    /// <summary>
    /// This is a unique number assigned to the customer for identification purposes. You may enter any combination of numbers and letters and if nothin entered it will be automatically generated by the system
    /// </summary>
    [JsonProperty("agreementNo", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
    [StringLength(20)]
    public string AgreementNo { get; set; }

    /// <summary>
    /// Lets you enter the accounting number.
    /// </summary>
    [JsonProperty("accountingNo", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
    [StringLength(20)]
    public string AccountingNo { get; set; }

    /// <summary>
    /// This time specifies when the contract comes into effect. if not set will be today.
    /// </summary>
    [JsonProperty("startDate", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
    [JsonConverter(typeof(DateFormatConverter))]
    public DateTimeOffset? StartDate { get; set; }

    /// <summary>
    /// The end date must be later than or equal to the start date.
    /// </summary>
    [JsonProperty("endDate", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
    [JsonConverter(typeof(DateFormatConverter))]
    public DateTimeOffset? EndDate { get; set; }

    [JsonProperty("defaultRemarks", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
    public Remarks DefaultRemarks { get; set; }

    /// <summary>
    /// If true, neutral cards will be included in the count.
    /// </summary>
    [JsonProperty("countNeutralCards", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
    public bool CountNeutralCards { get; set; }

    /// <summary>
    /// Specifies the maximum number of contract parkers of the associated customer that may be present at the parking facility at the same time. Once this maximum level is reached, any further contract parkers of this user will be denied entry.
    /// </summary>
    [JsonProperty("maxLevel", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
    [Range(int.MinValue, 9999)]
    public int? MaxLevel { get; set; }

    /// <summary>
    /// This will allow the contract parker to enter even if the maximum level has already been reached.
    /// </summary>
    [JsonProperty("enterOverMax", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
    public bool EnterOverMax { get; set; }

}
