// <auto-generated> — SKIDATA sweb Subscribe API model (do not edit by hand).
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace ParkingSubscription.Api.Subscribe;

[GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
public partial class Department
{
    /// <summary>
    /// Lets you enter the name of the contact’s business department. Will either create a new group if name doesn't exist or associate the contact with a new group
    /// </summary>
    [JsonProperty("name", Required = Required.Always)]
    [Required(AllowEmptyStrings = true)]
    [StringLength(64)]
    public string Name { get; set; }

    /// <summary>
    /// Lets you enter a description of the contact’s business department.
    /// </summary>
    [JsonProperty("description", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
    [StringLength(256)]
    public string Description { get; set; }

    private IDictionary<string, object> _additionalProperties;

    [JsonExtensionData]
    public IDictionary<string, object> AdditionalProperties
    {
        get { return _additionalProperties ?? (_additionalProperties = new Dictionary<string, object>()); }
        set { _additionalProperties = value; }
    }

}
