// <auto-generated> — SKIDATA sweb Subscribe API model (do not edit by hand).
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace ParkingSubscription.Api.Subscribe;

[GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
public partial class Details
{
    /// <summary>
    /// Surname to store on contact
    /// </summary>
    [JsonProperty("surname", Required = Required.Always)]
    [Required(AllowEmptyStrings = true)]
    [StringLength(64)]
    public string Surname { get; set; }

    /// <summary>
    /// the additional surname may be used e.g. for japanese culture where names in a second language are possible
    /// </summary>
    [JsonProperty("additionalSurname", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
    [StringLength(64)]
    public string AdditionalSurname { get; set; }

    /// <summary>
    /// Firstname to store on contact
    /// </summary>
    [JsonProperty("firstname", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
    [StringLength(64)]
    public string Firstname { get; set; }

    /// <summary>
    /// the additional firstname may be used e.g. for japanese culture where names in a second language are possible
    /// </summary>
    [JsonProperty("additionalFirstname", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
    [StringLength(64)]
    public string AdditionalFirstname { get; set; }

    /// <summary>
    /// Middlename to store on contact
    /// </summary>
    [JsonProperty("middlename", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
    [StringLength(64)]
    public string Middlename { get; set; }

    /// <summary>
    /// title to store on the contact
    /// </summary>
    [JsonProperty("title", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
    [StringLength(32)]
    public string Title { get; set; }

    /// <summary>
    /// The contact's short name
    /// </summary>
    [JsonProperty("abbreviation", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
    [StringLength(32)]
    public string Abbreviation { get; set; }

    /// <summary>
    /// the conatct's salutation
    /// </summary>
    [JsonProperty("salutation", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
    [StringLength(32)]
    public string Salutation { get; set; }

    /// <summary>
    /// Telephone to store on contact
    /// </summary>
    [JsonProperty("telephone", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
    [StringLength(64)]
    public string Telephone { get; set; }

    /// <summary>
    /// Mobile number to store on contact
    /// </summary>
    [JsonProperty("mobile", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
    [StringLength(64)]
    public string Mobile { get; set; }

    /// <summary>
    /// Fax to store on contact
    /// </summary>
    [JsonProperty("fax", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
    [StringLength(64)]
    public string Fax { get; set; }

    /// <summary>
    /// Email to store on contact
    /// </summary>
    [JsonProperty("email", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
    [StringLength(64)]
    public string Email { get; set; }

    /// <summary>
    /// The contact's date of Birth
    /// </summary>
    [JsonProperty("dateOfBirth", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
    [JsonConverter(typeof(DateFormatConverter))]
    public DateTimeOffset? DateOfBirth { get; set; }

    /// <summary>
    /// The ISO country code
    /// </summary>
    [JsonProperty("nationality", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
    [StringLength(64)]
    public string Nationality { get; set; }

    /// <summary>
    /// the spoken/preferred/default language of the contact
    /// </summary>
    [JsonProperty("language", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
    [StringLength(10)]
    public string Language { get; set; }

    [JsonProperty("gender", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
    [JsonConverter(typeof(StringEnumConverter))]
    public Gender? Gender { get; set; }

    /// <summary>
    /// Lets you enter the serial number of the customer’s ID document.
    /// </summary>
    [JsonProperty("legalIdentificationNumber", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
    [StringLength(64)]
    public string LegalIdentificationNumber { get; set; }

    private IDictionary<string, object> _additionalProperties;

    [JsonExtensionData]
    public IDictionary<string, object> AdditionalProperties
    {
        get { return _additionalProperties ?? (_additionalProperties = new Dictionary<string, object>()); }
        set { _additionalProperties = value; }
    }

}
