// <auto-generated> — SKIDATA sweb Subscribe API model (do not edit by hand).
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace ParkingSubscription.Api.Subscribe;

[GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
public partial class DoorAccess : Identification
{
    /// <summary>
    /// A code which can be enetered at a door reader for access.
    /// </summary>
    [JsonProperty("doorCode", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
    [StringLength(6)]
    public string DoorCode { get; set; }

}
