// <auto-generated> — SKIDATA sweb Subscribe API model (do not edit by hand).
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace ParkingSubscription.Api.Subscribe;

[GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
public enum EntryType
{

    [EnumMember(Value = @"ACCESS_NOT_GRANTED")]
    ACCESS_NOT_GRANTED = 0,

    [EnumMember(Value = @"ACCESS_GRANTED_WITH_TIMEWINDOW")]
    ACCESS_GRANTED_WITH_TIMEWINDOW = 1,

    [EnumMember(Value = @"ACCESS_GRANTED_NO_TIMEWINDOW")]
    ACCESS_GRANTED_NO_TIMEWINDOW = 2,

    [EnumMember(Value = @"ACCESS_GRANTED_WITH_TIMEWINDOW_CARPARK_FULL")]
    ACCESS_GRANTED_WITH_TIMEWINDOW_CARPARK_FULL = 3,

}
