// <auto-generated> — SKIDATA sweb Subscribe API model (do not edit by hand).
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace ParkingSubscription.Api.Subscribe;

[GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
public partial class GetUser : CreateUser
{
    [JsonProperty("userId", Required = Required.Always)]
    [Required(AllowEmptyStrings = true)]
    public Guid UserId { get; set; }

    [JsonProperty("lastUpdated", Required = Required.Always)]
    [Required(AllowEmptyStrings = true)]
    public DateTimeOffset LastUpdated { get; set; }

    /// <summary>
    /// This specifies the date when the user, including all their associated cards, will be blocked. This means they will no longer be authorized to enter or exit the facility.
    /// </summary>
    [JsonProperty("blockDate", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
    [JsonConverter(typeof(DateFormatConverter))]
    public DateTimeOffset? BlockDate { get; set; }

    [JsonProperty("suspension", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
    public Suspension Suspension { get; set; }

    /// <summary>
    /// This specifies the date when the user contact will expire. This date will be set when an anonymizeUser is done but the user contact still has valid subscriptions. After the expire date, no valid subscriptions etc. will exist and the user contact will get anonymized automatically and can then not be fetched anymore by getUser.
    /// </summary>
    [JsonProperty("expireDate", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
    [JsonConverter(typeof(DateFormatConverter))]
    public DateTimeOffset? ExpireDate { get; set; }

    /// <summary>
    /// Boolean flag that the user was marked as anonymized and overwritten with random values.
    /// </summary>
    [JsonProperty("anonymized", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
    public bool Anonymized { get; set; }

    /// <summary>
    /// Boolean flag that the user was marked as deleted.
    /// </summary>
    [JsonProperty("deleted", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
    public bool Deleted { get; set; }

}
