// <auto-generated> — SKIDATA sweb Subscribe API model (do not edit by hand).
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace ParkingSubscription.Api.Subscribe;

[GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
public partial class Identification
{
    /// <summary>
    /// This field must map to one of the GenericIdentification.type configured for the product, e.g. 'LP', 'EXT'
    /// </summary>
    [JsonProperty("type", Required = Required.Always)]
    [Required(AllowEmptyStrings = true)]
    [StringLength(256)]
    public string Type { get; set; }

    /// <summary>
    /// This field contains (depending on the Identification type) additional specification of the Identification, e.g. the ISO 3166 Alpha-2 (https://www.iban.com/country-codes) charcter country code for the type 'LP', the bar code format '15693' for the type 'EXT'. Provided by SKIDATA to match the configuration of the product references.
    /// </summary>
    [JsonProperty("subType", Required = Required.Always)]
    [Required(AllowEmptyStrings = true)]
    [StringLength(256)]
    public string SubType { get; set; }

    /// <summary>
    /// This field contains (depending on the Identification type) SKIDATA Identification number, credit card/debit card number, serial number of a key-card, serial number of an electronic purse, license plate, external card system and serial number of an external card system card or bank identification / account number
    /// </summary>
    [JsonProperty("value", Required = Required.Always)]
    [Required(AllowEmptyStrings = true)]
    [StringLength(256)]
    public string Value { get; set; }

    private IDictionary<string, object> _additionalProperties;

    [JsonExtensionData]
    public IDictionary<string, object> AdditionalProperties
    {
        get { return _additionalProperties ?? (_additionalProperties = new Dictionary<string, object>()); }
        set { _additionalProperties = value; }
    }

}
