// <auto-generated> — SKIDATA sweb Subscribe API model (do not edit by hand).
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace ParkingSubscription.Api.Subscribe;

[GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
public partial class LicensePlate
{
    /// <summary>
    /// This field contains the ISO 3166 Alpha-2 (https://www.iban.com/country-codes) character country code
    /// </summary>
    [JsonProperty("country", Required = Required.Always)]
    [Required(AllowEmptyStrings = true)]
    [StringLength(2)]
    public string Country { get; set; }

    /// <summary>
    /// The state within the country
    /// </summary>
    [JsonProperty("state", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
    [StringLength(32)]
    public string State { get; set; }

    /// <summary>
    /// LicensePlate number
    /// </summary>
    [JsonProperty("value", Required = Required.Always)]
    [Required(AllowEmptyStrings = true)]
    [StringLength(32)]
    public string Value { get; set; }

    /// <summary>
    /// The vehicle description
    /// </summary>
    [JsonProperty("vehicle", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
    [StringLength(64)]
    public string Vehicle { get; set; }

    private IDictionary<string, object> _additionalProperties;

    [JsonExtensionData]
    public IDictionary<string, object> AdditionalProperties
    {
        get { return _additionalProperties ?? (_additionalProperties = new Dictionary<string, object>()); }
        set { _additionalProperties = value; }
    }

}
