// <auto-generated> — SKIDATA sweb Subscribe API model (do not edit by hand).
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace ParkingSubscription.Api.Subscribe;

[GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
public partial class Remarks
{
    /// <summary>
    /// First remark to store next to user or customer parking contract for helpdesk support.
    /// </summary>
    [JsonProperty("remark1", Required = Required.Always)]
    [Required(AllowEmptyStrings = true)]
    [StringLength(50)]
    public string Remark1 { get; set; }

    /// <summary>
    /// Second remark to store next to  user or customer parking contract for helpdesk support.
    /// </summary>
    [JsonProperty("remark2", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
    [StringLength(50)]
    public string Remark2 { get; set; }

    /// <summary>
    /// Third remark to store next to  user or customer parking contract for helpdesk support.
    /// </summary>
    [JsonProperty("remark3", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
    [StringLength(50)]
    public string Remark3 { get; set; }

    private IDictionary<string, object> _additionalProperties;

    [JsonExtensionData]
    public IDictionary<string, object> AdditionalProperties
    {
        get { return _additionalProperties ?? (_additionalProperties = new Dictionary<string, object>()); }
        set { _additionalProperties = value; }
    }

}
