// <auto-generated> — SKIDATA sweb Subscribe API model (do not edit by hand).
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace ParkingSubscription.Api.Subscribe;

[GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
public partial class UpdateParkingCard : ManageIdentification
{
    /// <summary>
    /// Standard Parking Card 'validFrom' date.
    /// <br/>If not provided in request, system will use current day as default validFrom date.
    /// <br/>'validFrom' date must not overlap with other existing parking cards of an user.
    /// <br/>To be provided as localtime defined by RFC 3339, section 5.6.
    /// <br/>
    /// </summary>
    [JsonProperty("validFrom", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
    [JsonConverter(typeof(DateFormatConverter))]
    public DateTimeOffset? ValidFrom { get; set; }

    /// <summary>
    /// Standard Parking Card 'validTo' date.
    /// <br/>If not provided in request, system will use validFrom date and adds validity period value from TODO.
    /// <br/>'validTo' must be after 'validFrom', before or equals 'endDate' of customer and must
    /// <br/>overlap of other existing cards of an user.
    /// <br/>To be provided as localtime defined by RFC 3339, section 5.6.
    /// <br/>Must be before max date in ParkingLogic which is 31.12.2049.
    /// <br/>
    /// </summary>
    [JsonProperty("validTo", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
    [JsonConverter(typeof(DateFormatConverter))]
    public DateTimeOffset? ValidTo { get; set; }

    /// <summary>
    /// should the article be granted single neutral access permission.
    /// </summary>
    [JsonProperty("singleNeutral", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
    public bool SingleNeutral { get; set; }

    /// <summary>
    /// External reference to be stored on user to link with integrator system.
    /// </summary>
    [JsonProperty("externalCardId", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
    public string ExternalCardId { get; set; }

    [JsonProperty("carParks", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
    public ICollection<CarPark> CarParks { get; set; }

}
