// <auto-generated> — SKIDATA sweb Subscribe API model (do not edit by hand).
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace ParkingSubscription.Api.Subscribe;

[GeneratedCode("NJsonSchema", "14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0))")]
public partial class UserParkingContract
{
    /// <summary>
    /// The license plate is verified in combination with the card data at entrance and exit gates.
    /// </summary>
    [JsonProperty("checkLP", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
    public bool CheckLP { get; set; }

    /// <summary>
    /// Entry and exit permissions are verified exclusively via the vehicle license plate.
    /// </summary>
    [JsonProperty("passageLP", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
    public bool PassageLP { get; set; }

    /// <summary>
    /// The space which is allocated to the user.
    /// </summary>
    [JsonProperty("spaceNo", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
    [StringLength(5)]
    public string SpaceNo { get; set; }

    /// <summary>
    /// If true, the receipt will be e-mailed to the customer
    /// </summary>
    [JsonProperty("sendElectronicReceipt", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
    public bool SendElectronicReceipt { get; set; }

    /// <summary>
    /// Contract parkers who have multiple license plates registered on the system may only exit with the same license plate that was scanned upon entry.
    /// </summary>
    [JsonProperty("matchEntryPlate", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
    public bool MatchEntryPlate { get; set; }

    /// <summary>
    /// Include the user in group counts
    /// </summary>
    [JsonProperty("countUser", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
    public bool CountUser { get; set; }

    [JsonProperty("remarks", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
    public Remarks Remarks { get; set; }

    [JsonProperty("overtimeCustomerCreditCardSetting", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
    public OvertimeCustomerCreditCardSetting OvertimeCustomerCreditCardSetting { get; set; }

    private IDictionary<string, object> _additionalProperties;

    [JsonExtensionData]
    public IDictionary<string, object> AdditionalProperties
    {
        get { return _additionalProperties ?? (_additionalProperties = new Dictionary<string, object>()); }
        set { _additionalProperties = value; }
    }

}
