// Stamps src/buildInfo.ts with the app version, a build timestamp and the
// current git commit. Run this right before building an APK so the version
// shown in the app (Profile footer) matches the installed build.
//
//   node scripts/stamp-build.mjs
//
import { execSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');

const pkg = JSON.parse(readFileSync(resolve(root, 'package.json'), 'utf8'));

function git(cmd, fallback) {
  try {
    return execSync(`git ${cmd}`, { cwd: root, stdio: ['ignore', 'pipe', 'ignore'] })
      .toString()
      .trim();
  } catch {
    return fallback;
  }
}

const commit = git('rev-parse --short HEAD', 'nogit');
const build = git('rev-list --count HEAD', '0');
const dirty = git('status --porcelain', '') ? '+' : '';
// Local build date in YYYY-MM-DD HH:mm (24h), stable per build.
const now = new Date();
const pad = (n) => String(n).padStart(2, '0');
const stamp = `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())} ${pad(now.getHours())}:${pad(now.getMinutes())}`;

const out = `// AUTO-GENERATED by scripts/stamp-build.mjs — do not edit by hand.
export const BUILD_INFO = {
  version: '${pkg.version}',
  build: '${build}',
  commit: '${commit}${dirty}',
  builtAt: '${stamp}',
} as const;
`;

writeFileSync(resolve(root, 'src', 'buildInfo.ts'), out);
console.log(`Stamped v${pkg.version} · build ${build} · ${commit}${dirty} · ${stamp}`);
